<#
.SYNOPSIS
    Processes the log files generated by tests (deduplication, pruning, data structuring) and restores the source code.
.DESCRIPTION
    Requires the timestamp of the generated logs. Target folder and project folder are optional.
.EXAMPLE
    .\process-logs-demo.ps1 -t "20260329_171510"
#>

param (
    # Mandatory timestamp parameter
    [Parameter(Mandatory=$true, HelpMessage="Please enter the timestamp parameter, e.g., 20260329_171510")]
    [string]$t,

    # Optional target folder parameter for Git restore
    [Parameter(Mandatory=$false, HelpMessage="Specify the target folder path to restore")]
    [string]$TargetFolder = ".\demos\instrumentor-test\src\main\java\com\example\instrumentor\happens",

    # Optional project root directory for Block Pruner
    [Parameter(Mandatory=$false, HelpMessage="Specify the test project root directory")]
    [string]$ProjectFolder = "demos\instrumentor-test\"
)

# Verify path exists
if (-not (Test-Path $TargetFolder)) {
    Write-Error "Error: Target folder does not exist: $TargetFolder"
    exit 1
}

# Check Java environment variables
Write-Host "Checking Java environment variables..." -ForegroundColor Cyan
if (-not $env:JAVA_HOME) {
    Write-Error "Error: JAVA_HOME Environment variable not configured. Please set JAVA_HOME to point to your JDK installation directory."
    exit 1
}
Write-Host "Using JAVA_HOME: $env:JAVA_HOME" -ForegroundColor Green
$env:Path = "$env:JAVA_HOME\bin;$env:Path"

Write-Host "Starting log processing and data structuring (Current timestamp: $t)..." -ForegroundColor Cyan

# 1. Restore source code (Undo instrumentation modifications)
Write-Host "Restoring the instrumented source folder using Git..." -ForegroundColor Cyan
git restore $TargetFolder
git clean -fd $TargetFolder

# 2. Log Deduplication
Write-Host "Executing Log Deduplicator..." -ForegroundColor Yellow
java -jar .\demos\log-deduplicator\target\log-deduplicator-1.0-SNAPSHOT.jar .\instrumentor-log-${t}.txt .\instrumentor-log-${t}_dedup.txt

# 3. Block Pruner
Write-Host "Executing Block Pruner..." -ForegroundColor Yellow
java -jar .\demos\block-pruner\target\block-pruner-1.0-SNAPSHOT.jar $ProjectFolder .\comment-mapping.txt .\instrumentor-log-${t}_dedup.txt pruned\

# 4. Data Structuring
Write-Host "Executing Data Structuring..." -ForegroundColor Yellow
java -jar .\demos\data-structuring\target\data-structuring-1.0-SNAPSHOT.jar .\pruned\ .\comment-mapping.txt .\instrumentor-log-${t}_dedup.txt .\instrumentor-events-${t}.txt .\event_dictionary.txt

Write-Host "Log processing, data structuring, and source code restoration completed successfully!" -ForegroundColor Green