<#
.SYNOPSIS
    Processes the log files generated by tests (pruning, data structuring) and restores the source code.
.DESCRIPTION
    Accepts absolute (or relative) paths for all input/output files.
    Supports multiple target folders via a file or direct parameter, consistent with run-instrumentation-demo.ps1.
    The input log file is expected to be already deduplicated (e.g., produced by the JUnit listener).
.PARAMETER TargetFoldersFile
    Specifies a file containing target folder paths (one per line).
    Lines starting with '#' and empty lines are ignored.
    Defaults to '.\target-folders.txt'.
.PARAMETER TargetFolders
    Specifies one or more target folder paths (space-separated string or array).
    If specified, takes precedence over TargetFoldersFile.
.EXAMPLE
    .\process-logs-demo.ps1 `
        -LogFile "C:\logs\instrumentor-log-20260329_171510.txt" `
        -CommentMappingFile "C:\project\comment-mapping.txt" `
        -EventsFile "C:\output\instrumentor-events-20260329_171510.txt"
.EXAMPLE
    .\process-logs-demo.ps1 `
        -TargetFolders @(".\demos\project-a\src\main\java\com\example\a", ".\demos\project-b\src\main\java\com\example\b") `
        -LogFile ".\instrumentor-log.txt" `
        -CommentMappingFile ".\comment-mapping.txt" `
        -EventsFile ".\events.txt"
.EXAMPLE
    .\process-logs-demo.ps1 `
        -TargetFoldersFile ".\my-folders.txt" `
        -LogFile ".\instrumentor-log.txt" `
        -CommentMappingFile ".\comment-mapping.txt" `
        -EventsFile ".\events.txt"
#>

param (
    # File containing target folder paths (one per line), used if -TargetFolders is not specified
    [Parameter(Mandatory=$false, HelpMessage="Specify a file containing target folder paths (one per line)")]
    [string]$TargetFoldersFile = ".\target-folders.txt",

    # One or more target folder paths for git restore and as BlockPruner source directories
    [Parameter(Mandatory=$false, HelpMessage="Specify one or more target folder paths")]
    [string[]]$TargetFolders,

    # Path to the (already deduplicated) instrumentation log file (input)
    [Parameter(Mandatory=$true, HelpMessage="Path to the deduplicated instrumentation log file")]
    [string]$LogFile,

    # Path to the comment mapping file
    [Parameter(Mandatory=$true, HelpMessage="Path to the comment mapping file")]
    [string]$CommentMappingFile,

    # Path to the pruned output folder
    [Parameter(Mandatory=$false, HelpMessage="Path to the pruned output folder")]
    [string]$PrunedFolder = "pruned\",

    # Path to the structured events output file
    [Parameter(Mandatory=$true, HelpMessage="Path to the structured events output file")]
    [string]$EventsFile,

    # Path to the event dictionary output file
    [Parameter(Mandatory=$false, HelpMessage="Path to the event dictionary output file")]
    [string]$EventDictionaryFile = "event_dictionary.txt",

    # Optional path to the Block Pruner jar
    [Parameter(Mandatory=$false)]
    [string]$BlockPrunerJar = ".\demos\block-pruner\target\block-pruner-1.0-SNAPSHOT.jar",

    # Optional path to the Data Structuring jar
    [Parameter(Mandatory=$false)]
    [string]$DataStructuringJar = ".\demos\data-structuring\target\data-structuring-1.0-SNAPSHOT.jar"
)

# --- Resolve target folders (same pattern as run-instrumentation-demo.ps1) ---
if (-not $TargetFolders) {
    if (-not (Test-Path $TargetFoldersFile)) {
        Write-Error "Error: Target folders file does not exist: $TargetFoldersFile"
        exit 1
    }
    $TargetFolders = Get-Content $TargetFoldersFile | Where-Object {
        $_.Trim() -ne '' -and -not $_.TrimStart().StartsWith('#')
    }
    if ($TargetFolders.Count -eq 0) {
        Write-Error "Error: No target folders found in file: $TargetFoldersFile"
        exit 1
    }
    Write-Host "Loaded $($TargetFolders.Count) target folder(s) from file: $TargetFoldersFile" -ForegroundColor Yellow
}

foreach ($folder in $TargetFolders) {
    if (-not (Test-Path $folder)) {
        Write-Error "Error: Target folder does not exist: $folder"
        exit 1
    }
}
Write-Host "Target folders: $($TargetFolders -join ', ')" -ForegroundColor Yellow

# Verify critical input files exist
if (-not (Test-Path $LogFile)) {
    Write-Error "Error: Log file does not exist: $LogFile"
    exit 1
}

if (-not (Test-Path $CommentMappingFile)) {
    Write-Error "Error: Comment mapping file does not exist: $CommentMappingFile"
    exit 1
}

# Check Java environment variables
Write-Host "Checking Java environment variables..." -ForegroundColor Cyan
if (-not $env:JAVA_HOME) {
    Write-Error "Error: JAVA_HOME Environment variable not configured. Please set JAVA_HOME to point to your JDK installation directory."
    exit 1
}
Write-Host "Using JAVA_HOME: $env:JAVA_HOME" -ForegroundColor Green
$env:Path = "$env:JAVA_HOME\bin;$env:Path"

Write-Host "Starting log processing and data structuring..." -ForegroundColor Cyan
Write-Host "  TargetFolders:      $($TargetFolders -join '; ')" -ForegroundColor DarkGray
Write-Host "  LogFile:            $LogFile" -ForegroundColor DarkGray
Write-Host "  CommentMappingFile: $CommentMappingFile" -ForegroundColor DarkGray
Write-Host "  PrunedFolder:       $PrunedFolder" -ForegroundColor DarkGray
Write-Host "  EventsFile:         $EventsFile" -ForegroundColor DarkGray
Write-Host "  EventDictionaryFile:$EventDictionaryFile" -ForegroundColor DarkGray

# 1. Restore source code (Undo instrumentation modifications)
Write-Host "Restoring the instrumented source folders using Git..." -ForegroundColor Cyan
foreach ($folder in $TargetFolders) {
    git restore $folder
    git clean -fd $folder
}

# 2. Block Pruner — pass multiple source directories joined by ';'
Write-Host "Executing Block Pruner..." -ForegroundColor Yellow
$sourceDirsArg = ($TargetFolders -join ";")
java -jar $BlockPrunerJar $sourceDirsArg $CommentMappingFile $LogFile $PrunedFolder

# 3. Data Structuring
Write-Host "Executing Data Structuring..." -ForegroundColor Yellow
java -jar $DataStructuringJar $PrunedFolder $CommentMappingFile $LogFile $EventsFile $EventDictionaryFile

Write-Host "Log processing, data structuring, and source code restoration completed successfully!" -ForegroundColor Green